version: '3.1'

services:
  MovieReservation:
    build: movieReservation
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:mysql://db_movie_reservation:3306/movie_booking_db?serverTimezone=UTC
      BD_USER_NAME: user
      DB_PASSWORD: movieBooking123
    depends_on:
      db_movie_reservation:
        condition: service_healthy

  db_movie_reservation:
    container_name: movie_reservation_db
    image: mysql:8.0.33
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: movieBooking123
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: movie_booking_db
    ports:
      - 3307:3306
    expose:
        - 3306