version: '3.1'

services:
  app:
    container_name: movie_reservation_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db_movie_reservation:3306/movie_booking_db?createDatabaseIfNotExist=true&serverTimezone=UTC
        DB_USER_NAME: root
        DB_PASSWORD: root
    depends_on:
      db_movie_reservation:
        condition: service_healthy
    restart: unless-stopped

  db_movie_reservation:
    container_name: movie_reservation_db
    image: mysql:8.0.33
    ports:
      - "3309:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: movie_booking_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10